import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "./components/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-5/5 bg-[#FFFFFF] h-[64px] flex items-center p-8 shadow-custom relative z-20">
          <Logo/>
        </div>
  
        {children}
      </body>
    </html>
  );
}
